# configuration file for production environment

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1

plugins:
    Database:
        driver: 'mysql'
        database: 'leecarmi_radio'
        host: 'your_db_ip'
        #port: 3306
        username: 'leecarmi_radioro'
        password: 'change_me'
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 1


# app settings
enable_ga: 1
